export enum CombinationType {
  SINGLE = 'SINGLE',
  PAIR = 'PAIR',
  TRIPLE = 'TRIPLE',
  FOUR_OF_A_KIND = 'FOUR_OF_A_KIND',
  STRAIGHT = 'STRAIGHT',
  PAIR_STRAIGHT = 'PAIR_STRAIGHT',
  FOUR_CONSECUTIVE_PAIRS = 'FOUR_CONSECUTIVE_PAIRS',
}